### ISSUE TITLE
Bluesky => AP: Expire and refresh DID docs

### ISSUE THREAD

**Issue by ShreyanJain9** [snarfed/bridgy-fed#1201]
When bridging a Bluesky post including an image to AP, Bridgy uses the blob url from my *old* PDS, which doesn't have it and can't serve it. 

Bridgy is probably just not aware that my PDS migration ever happened, since there's not really an obvious sign of it to a service just consuming the Relay firehose and bridging the content to AP. Maybe this is something Bridgy should keep track of for bridged accounts, or it could use links to the AppView CDN instead of linking directly to the PDS blobs. I prefer the PDS approach, but using the CDN might be a much easier fix.

**Comment by snarfed** [comment]
Yup, your instincts are spot on, we just need to refresh our locally stored DID docs regularly. Should be straightforward!

**Comment by snarfed** [comment]
OK @ShreyanJain9 I've manually refreshed your DID doc. Mind trying again? If blobs work now, that confirms this hypothesis.

**Comment by ShreyanJain9** [comment]
They work exactly as expected now! Thank you 🫡

**Comment by Tamschi** [comment]
@snarfed This should be solved already, right? As long as Bridgy Fed also reacts to DID doc updates it sees for users who are bridged at the time, I mean.

**Comment by snarfed** [comment]
Sadly it's not really solved afaik. Bridgy Fed would need to subscribe to the PLC directory's audit log, https://github.com/did-method-plc/did-method-plc#audit-logs , which it doesn't yet do. Afaik there isn't a websocket stream there yet, so we'd need to poll.

Alternatively, the PDS _might_ emit `#account` events for DID doc changes - see #1119 - but I suspect not. Those aren't officially documented yet anyway. 😕

**Comment by snarfed** [comment]
`#account` etc events are now documented, https://atproto.com/specs/account#pds-account-migration , but I can't tell if PDS migrations or other DID doc updates generate `#account` events on the relay firehose. Hrm.

**Comment by snarfed** [comment]
Aha, https://github.com/bluesky-social/atproto/discussions/3175 has the answer:
> Overall, this means that account migration should result in three events coming from the relay: an #identity (from new PDS), an #account (from new PDS), and a #commit (from new PDS). The #account from the old PDS is usually ignored.

OK! So the conclusion here is probably that I should refresh DID docs on all `#account` and `#identity` events.

**Comment by snarfed** [comment]
Done! At least going forward. Existing accounts with stale DID docs can be refreshed by clicking the 🔁 button on their Bridgy Fed user page.
