### ISSUE TITLE
Fediverse account deleted and Bluesky username blocked

### ISSUE THREAD

**Issue by kandr3s** [snarfed/bridgy-fed#1525]
I bridged my website to Bluesky but then decided to disabled it so I could use the my domain (username) in the bsky.app instance. I added “#nobridge” to my description, I didn't know it would also delete my Fediverse account at @kandr3s@kandr3s.co

Now I can't use my domain on the Bluesky app and my Fediverse presence disappeared. Can this be fixed @snarfed?

I want to continue using Bridgy Fed for ActivityPub interactions and follow a more Bridgy Classic approach to Bluesky.

Thanks.

**Comment by snarfed** [comment]
Sorry for the trouble! Fixed now, we talked offline.

**Comment by kandr3s** [comment]
Thanks for the quick answer, @snarfed!

I still can't access my Brid.gy Fed ActivityPub (from the web) account: https://fed.brid.gy/web/kandr3s.co

My domain is still poiting to the web -> Brid.gy Fed Bluesky account. Which I want to delete completely so I can use my domain name as username on the Bluesky app.

When I try to re-add my website at https://fed.brid.gy/web-site I get:

`https://kandr3s.co/ is not a valid or supported web site`

And https://fed.brid.gy/kandr3s.co returns "web user kandr3s.co not found"

**Comment by snarfed** [comment]
Oops, you're right, sorry! OK, I've fixed all that now. Bluesky itself is struggling a bit right now, but the bridged Bluesky account should disappear soon.

(Also, you can switch kandr3s.co to be the handle for a new Bluesky account any time, you don't need to wait for me to do anything on Bridgy Fed's end.)
