### ISSUE TITLE
Avatar and header no longer visible

### ISSUE THREAD

**Issue by EmilJacobs** [snarfed/bridgy-fed#1763]
I noticed that my avatar and header are no longer loaded. I don't visit the bsky website regularly, so I'm not sure when this started, but the last major change on my instance was a move from local to object storage a few weeks ago. Could that be a trigger here?

Pictures in posts are however loaded as expected.

My profile: https://bsky.app/profile/collectifission.greennuclear.online.ap.brid.gy

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Yup, that move is probably the cause: https://fed.brid.gy/docs#bluesky-image-cdn

**Comment by Tamschi** [comment]
If that is indeed the case, then editing your profile in any way should fix it, by the way.
(Doing so sends out an `Update` activity that Bridgy Fed can translate into a Bluesky profile record update.)

It may be a good idea to mention that in the docs section.

**Comment by snarfed** [comment]
Oh interesting. If you think all image URLs on this instance changed, and the old ones no longer serve, and the instance didn't send `Update`s, then yes! That seems pretty destructive, and unlikely, but I guess possible.

**Comment by Tamschi** [comment]
I don't see how the instance *could* feasibly send updates to everyone who has cached its Objects. There's normally little to no tracking for that.

It should serve a Moved Permanently redirect on the old URLs, but there are definitely a few places this could fail in addition to the software itself not having that feature.

**Comment by snarfed** [comment]
Oh sure, I'm not arguing it's obligated to send updates to every known instance, but maybe at least to followers. Or, if the previous URLs redirect, that's fine too. But if you change a profile's or post's image URLs, _and_ the old URLs don't redirect, _and_ you don't send `Update`s...then you're going to have a bad time, regardless of bridges.

**Comment by Aelese** [comment]
I think something similar has been going on for weeks with an account bridged from a website. New posts are being pushed, so the bridge doesn't seem "stuck", but profile pic is not visible.

Website: https://pontevedra.gal/
Bridged account: https://bsky.app/profile/pontevedra.gal.web.brid.gy

PS: Sorry for hijacking the thread, I'm trying to avoid duplicates.

**Comment by EmilJacobs** [comment]
> If that is indeed the case, then editing your profile in any way should fix it, by the way. (Doing so sends out an `Update` activity that Bridgy Fed can translate into a Bluesky profile record update.)
> 
> It may be a good idea to mention that in the docs section.

Interesting: when selecting a different avatar, it syncs. But as soon as I go back, it's again no longer visible.

**Comment by snarfed** [comment]
Yes! Thanks @Tamschi, looks like this is indeed #1650.

@Aelese try the debugging steps in https://fed.brid.gy/docs#bluesky-image-cdn

**Comment by snarfed** [comment]
@EmilJacobs it's just a bug we need to fix, sorry. In the meantime, switching to a different image should fix it for you, as you saw. Even a single byte different will work, eg a slightly bigger or smaller version, or change the JPEG quality slightly, etc.

**Comment by Aelese** [comment]
> Yes! Thanks [@Tamschi](https://github.com/Tamschi), looks like [@EmilJacobs](https://github.com/EmilJacobs)'s profile at least is indeed [#1650](https://github.com/snarfed/bridgy-fed/issues/1650). Sorry Emil!
> 
> [@Aelese](https://github.com/Aelese) try the debugging steps in https://fed.brid.gy/docs#bluesky-image-cdn ?

A few days ago I tried to follow the steps and I couldn't get the link for any of the images as when using the browser's developer tools to inspect them, there wasn't even a link.

However, today I clicked on the avatar and inspected what should be the enlarged avatar, for which I got the following link: https://cdn.bsky.app/img/avatar/plain/did:plc:qr4hely5haxyanqepxpbapxb/bafkreibtbm6xg5sihydtcbehlqjjbkrfxlnbkukl2wdscouiwspnuj4z3y@jpeg. And yes, it seems to be the server's fault and I'll have to let it go as I don't have access to it.

Thanks for your help and sorry for the inconvenience.

**Comment by EmilJacobs** [comment]
> [@EmilJacobs](https://github.com/EmilJacobs) it's just a bug we need to fix, sorry. In the meantime, switching to a different image should fix it for you, as you saw. Even a single byte different will work, eg a slightly bigger or smaller version, or change the JPEG quality slightly, etc.

I did a re-export of the existing image, making sure it was a slight different size (a few kb less), but that didn't solve it. Odd?

**Comment by EmilJacobs** [comment]
Ok, recreated my avatar from scratch and this worked. Hope it keeps working.

**Comment by snarfed** [comment]
Glad it's working now!

**Comment by snarfed** [comment]
Duplicate of #1650
