### ISSUE TITLE
Web: Unable to find post after manual webmention

### ISSUE THREAD

**Issue by ch0ccyra1n** [snarfed/bridgy-fed#1835]
After sending [manual webmentions](https://fed.brid.gy/docs#web-how-post) for my [latest blog post](https://ch0ccyra1n.planetexpress.me/posts/my-thoughts-on-world-of-goo/) on my recently migrated website, I noticed a [lack of any posts showing up for it on bridgy-fed](https://fed.brid.gy/web/ch0ccyra1n.planetexpress.me/home). I did make sure that all of the webmention and microformat support is functional, but it seems to still not be able to pull it down. One possible reason could be that my posts are on a subdirectory, but I don't see why that should affect it. Another thing that could be related is that it couldn't find the RSS feed since as a [hugo](https://gohugo.io) site, it's located at an unusual uri (`/posts/index.xml`) but again, I don't *think* that should affect ability to show webmentions.

**Comment by snarfed** [comment]
Ugh, thanks for reporting! Looks like a bug on our end. Will investigate.

**Comment by snarfed** [comment]
Looks like the bug here is, if we fetch a URL for a link preview, and then later see it as a web post, we think we've already published it and don't do anything.

**Comment by ch0ccyra1n** [comment]
Hmm, oddly enough if I manually plug my post into `https://fed.brid.gy/r/[link-to-post]` and then open that with Mastodon, for example, it still shows up through federation. Same if I use `curl` with it to get the raw activitypub JSON:

```
curl -H 'Accept: application/activity+json' https://fed.brid.gy/r/https://ch0ccyra1n.planetexpress.me/posts/my-thoughts-on-world-of-goo/ | jq
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://purl.archive.org/miscellany"
  ],
  "attributedTo": "https://web.brid.gy/ch0ccyra1n.planetexpress.me",
  "content": "<p>World of Goo is an indie game developed by 2D Boy and published by Tomorrow Corporation.\nI first played this game back in 2008 on my Nintendo Wii,\nwhich I still have so I ended up playing it again on it. It was great to play games there again,\nas I had done all those years ago.\nIt’s a fantastic puzzle game built around physics, and I’m excited to share my thoughts.</p>\n<p>One thing I noticed right away was the aesthetic which is quite distinct and very morbid\nwhile also being cute and cartoony. It reminds me a bit of flash games I’d play back in the day,\nwhich makes sense since it released around that time. Everything in this game is dark, but still\nmade me laugh, as the game has a dark sense of humor that I didn’t get when I played it as a kid.\nIt’s truly something unique which you’ll have to see for yourself.</p>\n<p>Another thing I noticed about this game was that the controls on the Wii version were superb!\nPointing, clicking and dragging felt very natural, as this game was designed with the Wii in-mind.</p>\n<p>The gameplay involves the player building structures with the goo balls to lead them to a\npipe at the end of the level, and over time the puzzles become more and more complex.\nAs you do this, a fascinating story unfolds,\nwhich I won’t spoil here but it turns in some interesting directions.</p>\n<p>To conclude, World of Goo is an amazing game which I’m glad I revisited.\nEverything from the gameplay to the aesthetics reminds me of a simpler time\nwhen I played random WiiWare games all those years ago,\nand coming back to World of Goo allowed me to experience that joy once again.</p>\n<h4 id=\"verdict-recommended\">Verdict: Recommended!</h4>",
  "contentMap": {
    "en": "<p>World of Goo is an indie game developed by 2D Boy and published by Tomorrow Corporation.\nI first played this game back in 2008 on my Nintendo Wii,\nwhich I still have so I ended up playing it again on it. It was great to play games there again,\nas I had done all those years ago.\nIt’s a fantastic puzzle game built around physics, and I’m excited to share my thoughts.</p>\n<p>One thing I noticed right away was the aesthetic which is quite distinct and very morbid\nwhile also being cute and cartoony. It reminds me a bit of flash games I’d play back in the day,\nwhich makes sense since it released around that time. Everything in this game is dark, but still\nmade me laugh, as the game has a dark sense of humor that I didn’t get when I played it as a kid.\nIt’s truly something unique which you’ll have to see for yourself.</p>\n<p>Another thing I noticed about this game was that the controls on the Wii version were superb!\nPointing, clicking and dragging felt very natural, as this game was designed with the Wii in-mind.</p>\n<p>The gameplay involves the player building structures with the goo balls to lead them to a\npipe at the end of the level, and over time the puzzles become more and more complex.\nAs you do this, a fascinating story unfolds,\nwhich I won’t spoil here but it turns in some interesting directions.</p>\n<p>To conclude, World of Goo is an amazing game which I’m glad I revisited.\nEverything from the gameplay to the aesthetics reminds me of a simpler time\nwhen I played random WiiWare games all those years ago,\nand coming back to World of Goo allowed me to experience that joy once again.</p>\n<h4 id=\"verdict-recommended\">Verdict: Recommended!</h4>"
  },
  "id": "https://web.brid.gy/r/https://ch0ccyra1n.planetexpress.me/posts/my-thoughts-on-world-of-goo/",
  "name": "My Thoughts on World of Goo",
  "published": "2024-04-04T00:00:00",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "type": "Article",
  "url": "https://fed.brid.gy/r/https://ch0ccyra1n.planetexpress.me/posts/my-thoughts-on-world-of-goo/"
}
```

It *still* will not show up on the actual *bridgy-fed* page and I have no clue how that would be possible to do with Bluesky as-well, but at the very least this works as a hack to fix it on the fediverse end of things.

**Comment by snarfed** [comment]
Design-wise, internally, this is a bit ugly. If we've already loaded a web post before we see it via feed poll or webmention, we'll then load it as `new=False`, and its content will be unchanged, so we short circuit out of receive here:

https://github.com/snarfed/bridgy-fed/blob/69afabf1a2fec7f45b772571561a3f4268f93acd/protocol.py#L1339-L1341

I don't see an easy way around this yet, other than adding a new `Object.received` or `delivered` field that we'd store. Expensive ish though if we do that for all objects. Hrm.

**Comment by snarfed** [comment]
For anyone who hits this, you can force Bridgy Fed to bridge a post by [sending it via webmention](https://fed.brid.gy/docs#web-how-post) and adding `&force=true` to the webmention POST body.

**Comment by snarfed** [comment]
If we just drop the check for an existing `Object`, always refetch the source page, and then always send either a create or an update, depending on whether what we fetched is the same as what we have stored, that might fix this...?

**Comment by snarfed** [comment]
Done!
