### ISSUE TITLE
Not seeing follower on account page

### ISSUE THREAD

**Issue by aciccarello** [snarfed/bridgy-fed#279]
First of all, thanks for the user page. It makes it easy to see what activity is going on. I've been working on testing bridgy-fed with a mastodon account I have on toot.cafe. When I test following I can see that bridgy-fed receives the request but I noticed the follower count is still 0. Is something wrong? I've also tried to [like a mastodon post from my website](https://fed.brid.gy/log?start_time=1668218293&key=https://www.ciccarello.me/posts/2022/11/11/toot-like/%20https://toot.cafe/@aciccarello/109324149667546772&module=) but I'm also not seeing that appear in Mastodon. It's also entirely possible I've got something set up wrong.

https://fed.brid.gy/user/www.ciccarello.me

<img width="940" alt="image" src="https://user-images.githubusercontent.com/11273838/201590486-d91b5ab9-c780-4da5-b16a-326a5fb8cdbc.png">

**Comment by snarfed** [comment]
Hmm! Thanks for filing, will look.

**Comment by snarfed** [comment]
I suspect a bug with BF's custom username handling here, but only a suspicion right now.

**Comment by snarfed** [comment]
Looks like the missing follower on https://fed.brid.gy/user/www.ciccarello.me was just because I hadn't implemented storing inbound followers yet. I did that since your first follower, so now https://fed.brid.gy/user/www.ciccarello.me/followers is working. Feel free to try following from your account again.

**Comment by snarfed** [comment]
On the outbound like, I think I fixed one bug here, but another is probably that the `actor` is missing `id`. Here's the most recent log: https://fed.brid.gy/log?start_time=1668567102&key=https://www.ciccarello.me/posts/2022/11/11/toot-like/%20https://toot.cafe/@aciccarello/109324149667546772&module=

Oddly Mastodon might still work without `actor` and infer it from the HTTP sig `keyId`, but not here. https://socialhub.activitypub.rocks/t/do-some-implementations-infer-actor-from-http-signature-keyid/2661

**Comment by snarfed** [comment]
I _think_ adding `actor.id` fixed the like, the count on https://toot.cafe/@aciccarello/109324149667546772 went up to 2, but only on that home instance page, not on federated instances like https://indieweb.social/@aciccarello@toot.cafe/109324149692367200. I don't have an account on toot.cafe, and registration is closed. @aciccarello could you check that the like made it through successfully?

**Comment by snarfed** [comment]
I think these are both fixed. Please let me know if anything's still unhappy!

**Comment by aciccarello** [comment]
Thanks! I received the two likes on that tweet and your follow. I still don't see my (re)follow on bridgy's counter which seems strange. The logs seem to say it was accepted.

**Comment by snarfed** [comment]
Ah, thanks for the nudge! Looks like we weren't recovering well from broken existing follows. Should be fixed now, feel free to retry that follow.

**Comment by aciccarello** [comment]
Thanks so much for the quick fixes. My follow still doesn't appear to be working though.

**Comment by snarfed** [comment]
Argh, true. Thanks for your patience, I think I've fixed it now. https://fed.brid.gy/user/www.ciccarello.me/followers

**Comment by aciccarello** [comment]
Great! Thanks for tracking it down.
